// Mã lỗi dùng chung. Không tự chế mã mới trong route - thêm vào đây.
// Giữ các mã cũ (UNAUTHORIZED, FORBIDDEN, NOT_FOUND, VALIDATION, INTERNAL...) vì frontend đang đọc chúng.
export const ErrorCodes = {
  UNAUTHORIZED: "UNAUTHORIZED",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_TOKEN_REUSED: "AUTH_TOKEN_REUSED",
  FORBIDDEN: "FORBIDDEN",
  VALIDATION: "VALIDATION",
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  STATE_INVALID_TRANSITION: "STATE_INVALID_TRANSITION",
  MONEY_INSUFFICIENT_BALANCE: "MONEY_INSUFFICIENT_BALANCE",
  MONEY_INVALID_AMOUNT: "MONEY_INVALID_AMOUNT",
  EXTERNAL_SERVICE: "EXTERNAL_SERVICE",
  RATE_LIMITED: "RATE_LIMITED",
  INTERNAL: "INTERNAL",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes] | `${"NOT_FOUND" | "CONFLICT" | "STATE" | "MONEY" | "VALIDATION" | "EXTERNAL"}_${string}`;
