// Danh mục mã lỗi DUY NHẤT. AppError chỉ nhận mã có ở đây (typecheck chặn mã tự chế trong route).
// Mã cũ giữ nguyên chuỗi vì frontend/MCP đang so sánh (vd TOKEN_EXPIRED, HAS_PAYMENTS, CARTON_LOCKED).
// Mã mới nên theo nhóm AUTH_* / PERMISSION_* / VALIDATION_* / NOT_FOUND_* / CONFLICT_* / STATE_* / MONEY_* / EXTERNAL_*.
export const ErrorCodes = [
  // Xác thực / phân quyền
  "UNAUTHORIZED", "TOKEN_EXPIRED", "INVALID_TOKEN", "REVOKED", "INVALID_API_KEY",
  "INVALID_CREDENTIALS", "INVALID_REFRESH", "NO_REFRESH", "TOKEN_REUSE", "WRONG_OLD_PASSWORD", "BAD_TOKEN", "BAD_KEY",
  "AUTH_INVALID_CREDENTIALS", "AUTH_TOKEN_REUSED",
  "FORBIDDEN", "PROTECTED", "CANNOT_DELETE_SELF",
  // 2FA (TOTP)
  "TWO_FACTOR_SETUP_REQUIRED", "TWO_FACTOR_INVALID_CODE", "TWO_FACTOR_CODE_REUSED", "TWO_FACTOR_CHALLENGE_INVALID",
  "TWO_FACTOR_TOO_MANY_ATTEMPTS", "TWO_FACTOR_ALREADY_ENABLED", "TWO_FACTOR_NOT_ENABLED", "TWO_FACTOR_NOT_PENDING",
  "TWO_FACTOR_NOT_CONFIGURED",
  // Dữ liệu vào
  "VALIDATION", "BAD_REQUEST", "BAD_URL", "BAD_FILE", "BAD_CATEGORY", "FILE_TOO_LARGE",
  "MISSING_COUNT", "MISSING_TOTALS", "WRONG_MARKETPLACE", "NOT_YAHOO", "CURRENCY_MISMATCH", "SAME_WALLET",
  // Không tìm thấy
  "NOT_FOUND", "ORDER_NOT_FOUND", "WALLET_NOT_FOUND", "NO_SHEET",
  // Xung đột / trạng thái
  "CONFLICT", "EMAIL_EXISTS", "ROLE_EXISTS", "WALLET_EXISTS", "BUSY", "LOCKED", "CARTON_LOCKED",
  "HAS_DEBTS", "HAS_DEPOSITS", "HAS_ORDERS", "HAS_PAYMENTS", "HAS_TXNS", "TRACKING_HAS_COST", "TRACKING_HAS_COMPANY_COST",
  "ALREADY_PAID", "NOT_PAID", "NOT_REVOKED",
  "STATE_INVALID_TRANSITION", "STATE_CONFLICT", "CONFLICT_DUPLICATE_FILE", "CONFLICT_ALREADY_RECONCILED",
  // Tiền
  "MONEY_INSUFFICIENT_BALANCE", "MONEY_INVALID_AMOUNT",
  // Bên ngoài / hệ thống
  "EXTERNAL_SERVICE", "FETCH_FAILED", "DOWNLOAD_FAILED", "NOT_IMPLEMENTED", "RATE_LIMITED", "INTERNAL",
] as const;

export type ErrorCode = (typeof ErrorCodes)[number];
